(use-modules (smartcols))

;;; (init-debug #xFFFF)
(define t (make-table))
(define name-col (new-column! t "NAME" 0 0))
(define age-col (new-column! t "AGE"  0 0))
(define gdad (new-line! t))
(set-data! gdad (0 "Grandfather Bob"))
(set-data! gdad (1 "61"))
(define dad (new-line-child! t gdad))
(set-data! dad (0 "Father Adam"))
(set-data! dad (1 "38"))
(define baby-val (new-line-child! t dad))
(set-data! baby-val (0 "Baby Val"))
(set-data! baby-val (1 "9"))
(define baby-dilbert (new-line-child! t dad))
(set-data! baby-dilbert (0 "Baby Dilbert"))
(set-data! baby-dilbert (1 "5"))
(define aunt-gaga (new-line-child! t gdad))
(set-data! aunt-gaga (0 "Aunt Gaga"))
(set-data! aunt-gaga (1 "35"))

(print-table t)
